ERROR - 2024-11-10 12:35:13 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:35:13 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:35:13 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:36:11 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:36:11 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:36:11 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:38:51 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:38:51 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:38:51 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:39:55 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:39:55 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:39:55 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:40:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:40:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:40:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:41:32 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:41:32 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:41:32 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:43:17 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:43:17 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:43:17 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:45:04 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:45:04 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:45:04 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:45:23 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:45:23 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:45:23 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:49:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:49:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:49:44 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:49:54 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:49:54 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:49:54 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:51:15 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:51:15 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:51:15 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
ERROR - 2024-11-10 12:53:00 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 49
ERROR - 2024-11-10 12:53:00 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 83
ERROR - 2024-11-10 12:53:00 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given D:\xampp\htdocs\surepay\app\modules\admin\models\Staffs_model.php 113
