<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-08-30 04:52:18 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 04:52:22 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 04:52:24 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 04:52:32 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 04:53:14 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 04:53:19 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:06:02 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:06:04 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:06:14 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:06:17 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:07:38 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:07:40 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:07:43 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:07:49 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:08 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:08 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:23 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:23 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:25 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:27 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:28 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:28 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:30 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:31 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:32 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:33 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:35 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:36 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:40 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:40 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:41 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:41 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:42 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:42 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:43 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:43 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:43 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:43 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:44 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:44 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:44 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:44 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:44 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:45 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:37:45 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:48:34 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:48:36 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:48:41 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:49:08 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:49:58 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:50:00 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:50:02 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
ERROR - 2024-08-30 05:50:02 --> Severity: error --> Exception: syntax error, unexpected end of file /home/superpay/public_html/app/modules/auth/controllers/Auth.php 514
